FROM certbot/certbot:v2.10.0
LABEL maintainer="Shervin Gouhari <shervingouhari@gmail.com>"
COPY launch-certbot.sh /usr/local/bin/launch-certbot.sh
RUN chmod +x /usr/local/bin/launch-certbot.sh
ENTRYPOINT []
CMD ["launch-certbot.sh"]
